# Chapter 5 - Basic Math and Statistics
## Segment 3 - Generating summary statistics using pandas and scipy

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

import scipy
from scipy import stats

In [2]:
address = r'C:\Users\sp\Downloads\09Python Datascience Essentials part1\Datascience Essentials1 Exercise Files\Data\mtcars.csv'

cars = pd.read_csv(address)
cars.columns = ['car_names','mpg','cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb']

cars.head()

,car_names,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

### Looking at summary statistics that decribe a variable's numeric values

In [3]:
cars.sum()

car_names    Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...
mpg                                                      642.9
cyl                                                        198
disp                                                    7383.1
hp                                                        4694
drat                                                    115.09
wt                                                     102.952
qsec                                                    571.16
vs                                                          14
am                                                          13
gear                                                       118
carb                                                        90
dtype: object

In [4]:
cars.sum(axis=1)

0     328.980
1     329.795
2     259.580
3     426.135
4     590.310
5     385.540
6     656.920
7     270.980
8     299.570
9     350.460
10    349.660
11    510.740
12    511.500
13    509.850
14    728.560
15    726.644
16    725.695
17    213.850
18    195.165
19    206.955
20    273.775
21    519.650
22    506.085
23    646.280
24    631.175
25    208.215
26    272.570
27    273.683
28    670.690
29    379.590
30    694.710
31    288.890
dtype: float64

In [5]:
cars.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [6]:
cars.mean()

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [7]:
cars.max()

car_names    Volvo 142E
mpg                33.9
cyl                   8
disp                472
hp                  335
drat               4.93
wt                5.424
qsec               22.9
vs                    1
am                    1
gear                  5
carb                  8
dtype: object

In [11]:
mpg = cars.mpg
mpg.idxmax()

19

### Looking at summary statistics that describe variable distribution

In [12]:
cars.std()

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [13]:
cars.var()

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

In [14]:
gear = cars.gear
gear.value_counts()

3    15
4    12
5     5
Name: gear, dtype: int64

In [15]:
cars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [16]:
cars.skew()

mpg     0.672377
cyl    -0.192261
disp    0.420233
hp      0.799407
drat    0.292780
wt      0.465916
qsec    0.406347
vs      0.264542
am      0.400809
gear    0.582309
carb    1.157091
dtype: float64

In [17]:
cars.kurt()

mpg    -0.022006
cyl    -1.762794
disp   -1.067523
hp      0.275212
drat   -0.450432
wt      0.416595
qsec    0.864931
vs     -2.063273
am     -1.966550
gear   -0.895292
carb    2.020059
dtype: float64

In [21]:
cars.cov()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
mpg,36.324103,-9.172379,-633.097208,-320.732056,2.195064,-5.116685,4.509149,2.017137,1.803931,2.135685,-5.363105
cyl,-9.172379,3.189516,199.660282,101.931452,-0.668367,1.367371,-1.886855,-0.729839,-0.465726,-0.649194,1.520161
disp,-633.097208,199.660282,15360.799829,6721.158669,-47.064019,107.684204,-96.051681,-44.377621,-36.564012,-50.802621,79.068750
hp,-320.732056,101.931452,6721.158669,4700.866935,-16.451109,44.192661,-86.770081,-24.987903,-8.320565,-6.358871,83.036290
drat,2.195064,-0.668367,-47.064019,-16.451109,0.285881,-0.372721,0.087141,0.118649,0.190151,0.275988,-0.078407
wt,-5.116685,1.367371,107.684204,44.192661,-0.372721,0.957379,-0.305482,-0.273661,-0.338105,-0.421081,0.675790
qsec,4.509149,-1.886855,-96.051681,-86.770081,0.087141,-0.305482,3.193166,0.670565,-0.204960,-0.280403,-1.894113
vs,2.017137,-0.729839,-44.377621,-24.987903,0.118649,-0.273661,0.670565,0.254032,0.042339,0.076613,-0.463710
am,1.803931,-0.465726,-36.564012,-8.320565,0.190151,-0.338105,-0.204960,0.042339,0.248992,0.292339,0.046371
gear,2.135685,-0.649194,-50.802621,-6.358871,0.275988,-0.421081,-0.280403,0.076613,0.292339,0.544355,0.326613
carb,-5.363105,1.520161,79.068750,83.036290,-0.078407,0.675790,-1.894113,-0.463710,0.046371,0.326613,2.608871

In [22]:
cars.cumsum()

,car_names,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4Mazda RX4 Wag,42.0,12,320.0,220,7.80,5.495,33.48,0,2,8,8
2,Mazda RX4Mazda RX4 WagDatsun 710,64.8,16,428.0,313,11.65,7.815,52.09,1,3,12,9
3,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive,86.2,22,686.0,423,14.73,11.030,71.53,2,3,15,10
4,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,104.9,30,1046.0,598,17.88,14.470,88.55,2,3,18,12
5,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,123.0,36,1271.0,703,20.64,17.930,108.77,3,3,21,13
6,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,137.3,44,1631.0,948,23.85,21.500,124.61,3,3,24,17
7,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,161.7,48,1777.7,1010,27.54,24.690,144.61,4,3,28,19
8,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,184.5,52,1918.5,1105,31.46,27.840,167.51,5,3,32,21
9,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,203.7,58,2086.1,1228,35.38,31.280,185.81,6,3,36,25
10,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,221.5,64,2253.7,1351,39.30,34.720,204.71,7,3,40,29
11,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,237.9,72,2529.5,1531,42.37,38.790,222.11,7,3,43,32
12,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,255.2,80,2805.3,1711,45.44,42.520,239.71,7,3,46,35
13,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,270.4,88,3081.1,1891,48.51,46.300,257.71,7,3,49,38
14,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,280.8,96,3553.1,2096,51.44,51.550,275.69,7,3,52,42
15,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,291.2,104,4013.1,2311,54.44,56.974,293.51,7,3,55,46
16,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,305.9,112,4453.1,2541,57.67,62.319,310.93,7,3,58,50
17,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,338.3,116,4531.8,2607,61.75,64.519,330.40,8,4,62,51
18,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,368.7,120,4607.5,2659,66.68,66.134,348.92,9,5,66,53
19,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,402.6,124,4678.6,2724,70.90,67.969,368.82,10,6,70,54
20,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,424.1,128,4798.7,2821,74.60,70.434,388.83,11,6,73,55
21,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,439.6,136,5116.7,2971,77.36,73.954,405.70,11,6,76,57
22,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,454.8,144,5420.7,3121,80.51,77.389,423.00,11,6,79,59
23,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,468.1,152,5770.7,3366,84.24,81.229,438.41,11,6,82,63
24,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,487.3,160,6170.7,3541,87.32,85.074,455.46,11,6,85,65
25,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,514.6,164,6249.7,3607,91.40,87.009,474.36,12,7,89,66
26,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,540.6,168,6370.0,3698,95.83,89.149,491.06,12,8,94,68
27,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,571.0,172,6465.1,3811,99.60,90.662,507.96,13,9,99,70
28,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,586.8,180,6816.1,4075,103.82,93.832,522.46,13,10,104,74
29,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,606.5,186,6961.1,4250,107.44,96.602,537.96,13,11,109,80
30,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,621.5,194,7262.1,4585,110.98,100.172,552.56,13,12,114,88
31,Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...,642.9,198,7383.1,4694,115.09,102.952,571.16,14,13,118,90

In [29]:
cars.cummax()

,car_names,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Mazda RX4 Wag,22.8,6,160.0,110,3.90,2.875,18.61,1,1,4,4
3,Mazda RX4 Wag,22.8,6,258.0,110,3.90,3.215,19.44,1,1,4,4
4,Mazda RX4 Wag,22.8,8,360.0,175,3.90,3.440,19.44,1,1,4,4
5,Valiant,22.8,8,360.0,175,3.90,3.460,20.22,1,1,4,4
6,Valiant,22.8,8,360.0,245,3.90,3.570,20.22,1,1,4,4
7,Valiant,24.4,8,360.0,245,3.90,3.570,20.22,1,1,4,4
8,Valiant,24.4,8,360.0,245,3.92,3.570,22.90,1,1,4,4
9,Valiant,24.4,8,360.0,245,3.92,3.570,22.90,1,1,4,4
10,Valiant,24.4,8,360.0,245,3.92,3.570,22.90,1,1,4,4
11,Valiant,24.4,8,360.0,245,3.92,4.070,22.90,1,1,4,4
12,Valiant,24.4,8,360.0,245,3.92,4.070,22.90,1,1,4,4
13,Valiant,24.4,8,360.0,245,3.92,4.070,22.90,1,1,4,4
14,Valiant,24.4,8,472.0,245,3.92,5.250,22.90,1,1,4,4
15,Valiant,24.4,8,472.0,245,3.92,5.424,22.90,1,1,4,4
16,Valiant,24.4,8,472.0,245,3.92,5.424,22.90,1,1,4,4
17,Valiant,32.4,8,472.0,245,4.08,5.424,22.90,1,1,4,4
18,Valiant,32.4,8,472.0,245,4.93,5.424,22.90,1,1,4,4
19,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,4,4
20,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,4,4
21,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,4,4
22,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,4,4
23,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,4,4
24,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,4,4
25,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,4,4
26,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,5,4
27,Valiant,33.9,8,472.0,245,4.93,5.424,22.90,1,1,5,4
28,Valiant,33.9,8,472.0,264,4.93,5.424,22.90,1,1,5,4
29,Valiant,33.9,8,472.0,264,4.93,5.424,22.90,1,1,5,6
30,Valiant,33.9,8,472.0,335,4.93,5.424,22.90,1,1,5,8
31,Volvo 142E,33.9,8,472.0,335,4.93,5.424,22.90,1,1,5,8

In [32]:
cars.drop_duplicates()

,car_names,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [34]:
cars.drat

0     3.90
1     3.90
2     3.85
3     3.08
4     3.15
5     2.76
6     3.21
7     3.69
8     3.92
9     3.92
10    3.92
11    3.07
12    3.07
13    3.07
14    2.93
15    3.00
16    3.23
17    4.08
18    4.93
19    4.22
20    3.70
21    2.76
22    3.15
23    3.73
24    3.08
25    4.08
26    4.43
27    3.77
28    4.22
29    3.62
30    3.54
31    4.11
Name: drat, dtype: float64